name: Build tank-client

on:
  push:
    tags:
      - "v*.*.*"
      - "latest"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        platform: [linux]
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel
        python setup.py egg_info
        pip install -r *.egg-info/requires.txt
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Set env
      run: echo "RELEASE_VERSION=$(python setup.py -V)" >> $GITHUB_ENV
    - name: Test env
      run: echo ${RELEASE_VERSION}
    - name: build
      run: python setup.py bdist_wheel
    - name: Upload Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./dist/tank-${{ env.RELEASE_VERSION }}-py3-none-${{matrix.platform}}.whl
        asset_name: "tank-${{ env.RELEASE_VERSION }}-py3-none-${{matrix.platform}}.whl"
        overwrite: true
        tag: ${{ github.ref }}
        prerelease: false
        repo_name: DarwinsBuddy/tank-client
